### ISSUE TITLE
somebody can help me

### ISSUE THREAD

**Issue by alimalls** [csxmli2016/DFDNet#73]
i try to run the test_facedict.py ,How to fix the following errors.

F:\DFDNet-whole>python test_FaceDict.py --test_path ./TestData/TestWhole --resu
ts_dir ./Results/TestWholeResults --upscale_factor 4 --gpu_ids 0
Traceback (most recent call last):
  File "test_FaceDict.py", line 2, in <module>
    from options.test_options import TestOptions
  File "F:\DFDNet-whole\options\test_options.py", line 1, in <module>
    from .base_options import BaseOptions
  File "F:\DFDNet-whole\options\base_options.py", line 3, in <module>
    from util import util
  File "F:\DFDNet-whole\util\util.py", line 7, in <module>
    import torchvision
ModuleNotFoundError: No module named 'torchvision'

**Comment by gabgren** [comment]
Fore future reference:

The important line is >ModuleNotFoundError: No module named 'torchvision'

torchvision is not installed. do:

pip install torchvision
